apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  NODE_ENV: "production"
  MYSQL_HOST: "mysql"
  MYSQL_DB: "appdb"
  MONGO_URI: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo/appdb?replicaSet=rs0"
